name: test-install-script

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test-install-script:
    name: Test install script for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: test install script
        run: |
          curl -s https://raw.githubusercontent.com/francis-du/iotdb-cli/main/install.sh | sh
          curl -s https://raw.githubusercontent.com/francis-du/iotdb-cli/main/install.sh | sh